-- supabase/setup_schema.sql
-- Run this in your Supabase SQL Editor to create the contacted_clients table
-- This table is designed to log clients who have been successfully messaged or replied.

CREATE TABLE contacted_clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_name TEXT NOT NULL,
  email TEXT NOT NULL,
  website_url TEXT,
  specific_problem TEXT,
  email_subject TEXT,
  email_body TEXT,
  status TEXT DEFAULT 'messaged', -- Can be 'messaged', 'replied', etc.
  messaged_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for quick lookups by email to prevent double-messaging
CREATE UNIQUE INDEX idx_contacted_clients_email ON contacted_clients(email);
